apiVersion: v1
kind: Service
metadata:
  name: brain-app-service
spec:
  selector:
    app: brain-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-app
  template:
    metadata:
      labels:
        app: brain-app
    spec:
      containers:
        - name: project-1-app
          image: ragulgandhi/brain-app1:latest
          ports:
            - containerPort: 80
